<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MatchForecast.Logger</RootNamespace>
  </PropertyGroup>

  <!-- NLog packages -->
  <ItemGroup>
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
  </ItemGroup>

  <!-- Models for ForecastException -->
  <ItemGroup>
    <ProjectReference Include="..\MatchForecast.Models\MatchForecast.Models.csproj" />
  </ItemGroup>

  <!-- Copy nlog.config to output -->
  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
